/*
 * Module 2
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BillingSystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.awt.Dimension;

/**
 *
 
 */
public class Registrationform extends javax.swing.JFrame {

    
     // Creates new form Registrationform
     
    public Registrationform() {
    	setPreferredSize(new Dimension(1920, 1080));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        confirmphone = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        confirmconsumerno = new javax.swing.JPasswordField();
        consumerno = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);
       // jPanel1.bounds();

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Registration Form For Electricity Billing");
        jPanel1.add(jLabel1);
   
        jLabel1.setBounds(100, 20, 600, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 20, 820, 100);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("CONSUMERNO");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 250, 160, 40);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setText("FIRST NAME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(110, 50, 170, 40);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("LAST NAME");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(110, 100, 170, 40);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setText("PHONE NO");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(110, 150, 170, 40);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setText("CONFIRM CONSUMERNO");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(110, 300, 230, 40);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setText("CONFIRM PHONE NO");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 200, 236, 40);

        lastname.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel2.add(lastname);
        lastname.setBounds(380, 110, 200, 30);

        phone.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel2.add(phone);
        phone.setBounds(380, 160, 200, 30);

        confirmphone.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel2.add(confirmphone);
        confirmphone.setBounds(380, 210, 200, 30);

        firstname.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jPanel2.add(firstname);
        firstname.setBounds(380, 60, 200, 30);

        confirmconsumerno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpasswordActionPerformed(evt);
            }
        });
        jPanel2.add(confirmconsumerno);
        confirmconsumerno.setBounds(380, 300, 200, 30);
        jPanel2.add(consumerno);
        consumerno.setBounds(380, 260, 200, 30);

        jButton1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(490, 380, 100, 40);

        jButton2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					jButton2ActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(260, 380, 100, 40);

        jButton3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(380, 380, 100, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(150, 130, 820, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpasswordActionPerformed
       
    }//GEN-LAST:event_confirmpasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        SystemBilling  BillingSystem= new SystemBilling();
        insertDataIntoDB();
            BillingSystem.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        firstname.setText("");
        lastname.setText("");
        phone.setText("");
        confirmphone.setText("");
        consumerno.setText("");
        confirmconsumerno.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JTextField confirmphone;
    private javax.swing.JPasswordField confirmconsumerno;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField lastname;
    private javax.swing.JPasswordField consumerno;
    // End of variables declaration
    
    public void insertDataIntoDB() throws Exception
    {
    	Connection con;
    	Statement stat;
    	Class.forName("com.mysql.jdbc.Driver"); //register the driver
    	 con =DriverManager.getConnection("jdbc:mysql://localhost:3306/test3","root","");  //establish the connection
     	stat=  con.createStatement(); //create a statement ,static sql statement
     	
     	String query = null;
 		query = "insert into reg values('"+ firstname.getText() + "','"+ lastname.getText()+"','"+ phone.getText() +"','"+ consumerno.getText() +"')";
 		stat.executeUpdate(query); //execute sql commands on database and update it to database
 		con.close(); // closing the connection
    }
    }
